# Only local deploy
version: '3.1'

services:

  db-phone:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "phonedb"
      POSTGRES_USER: "user_phone"
      POSTGRES_PASSWORD: "12345"
    volumes:
        - ./data/postgres:/var/lib/postgresql/data